version: '3.1'
services:
    redis:
        image: 'redis:3.2.7'
        container_name: redis_container
        restart: always
        ports:
            - "6379:6379"
        # command: redis-server --requirepass redispass

    mysqldb:
        image: mysql
        container_name: mysql_container
        hostname: mysql_host
        ports:
            - "3306:3306"
        restart: always
        volumes:
            - /var/lib/app/mysql_container:/var/lib/mysql
        environment:
          MYSQL_ROOT_PASSWORD: $ROOT_PASSWORD
          MYSQL_DATABASE: airflow_db
          MYSQL_USER: mysqluser
          MYSQL_PASSWORD: mysql123
        command: --default-authentication-plugin=mysql_native_password
        env_file:
            - .env

    webserver:
        image: sample
        container_name: airflow_webserver
        restart: always
        depends_on:
            - mysqldb
            - redis
        environment:
          LOAD_EX: y
          AIRFLOW__WEBSERVER__RBAC: "true"
          FERNET_KEY: oCBMIgh/IAeTJgLV3RiHdKxYDsTx7Cpo18++sDD5SIc=
          EXECUTOR: Celery
          AIRFLOW_CONN_AIRFLOW_DB: mysql://root:${ROOT_PASSWORD}@mysql_container:3306/airflow_db
          AIRFLOW__CORE__SQL_ALCHEMY_CONN: mysql://root:${ROOT_PASSWORD}@mysql_container:3306/airflow_db
          AIRFLOW__CELERY__RESULT_BACKEND: db+mysql://root:${ROOT_PASSWORD}@mysql_container:3306/airflow_db
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
            # - REDIS_PASSWORD=redispass
        volumes:
            - /home/engsptvm/docker-airflow/dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        env_file:
            - .env

    flower:  
        image: sample
        container_name: airflow_flower
        restart: always
        depends_on:
            - redis
        environment:
          EXECUTOR: Celery
          FERNET_KEY: oCBMIgh/IAeTJgLV3RiHdKxYDsTx7Cpo18++sDD5SIc=
          AIRFLOW__CORE__SQL_ALCHEMY_CONN: mysql://root:${ROOT_PASSWORD}@mysql_container:3306/airflow_db
          AIRFLOW__CELERY__RESULT_BACKEND: db+mysql://root:${ROOT_PASSWORD}@mysql_container:3306/airflow_db
            #- REDIS_PASSWORD=redispass
        ports:
            - "5555:5555"
        command: flower
        env_file:
            - .env

    scheduler:
        image: sample
        container_name: airflow_scheduler
        restart: always
        depends_on:
            - webserver
        volumes:
            - /home/engsptvm/docker-airflow/dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        environment:
          LOAD_EX: y
          EXECUTOR: Celery
          FERNET_KEY: oCBMIgh/IAeTJgLV3RiHdKxYDsTx7Cpo18++sDD5SIc=
          AIRFLOW__CORE__SQL_ALCHEMY_CONN: mysql://root:${ROOT_PASSWORD}@mysql_container:3306/airflow_db
          AIRFLOW__CELERY__RESULT_BACKEND: db+mysql://root:${ROOT_PASSWORD}@mysql_container:3306/airflow_db
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
            # - REDIS_PASSWORD=redispass
        command: scheduler
        env_file:
            - .env

    worker1:
        image: sample
        container_name: airflow_worker1
        restart: always
        depends_on:
            - scheduler
        volumes:
            - /home/engsptvm/docker-airflow/dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        environment:
          EXECUTOR: Celery
          FERNET_KEY: oCBMIgh/IAeTJgLV3RiHdKxYDsTx7Cpo18++sDD5SIc=
          AIRFLOW__CORE__SQL_ALCHEMY_CONN: mysql://root:${ROOT_PASSWORD}@mysql_container:3306/airflow_db
          AIRFLOW__CELERY__RESULT_BACKEND: db+mysql://root:${ROOT_PASSWORD}@mysql_container:3306/airflow_db
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
            # - REDIS_PASSWORD=redispass
        command: worker
        env_file:
            - .env

    worker2:
        image: sample
        container_name: airflow_worker2
        restart: always
        depends_on:
            - scheduler
        volumes:
            - /home/engsptvm/docker-airflow/dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        environment:
          EXECUTOR: Celery
          FERNET_KEY: oCBMIgh/IAeTJgLV3RiHdKxYDsTx7Cpo18++sDD5SIc=
          AIRFLOW__CORE__SQL_ALCHEMY_CONN: mysql://root:${ROOT_PASSWORD}@mysql_container:3306/airflow_db
          AIRFLOW__CELERY__RESULT_BACKEND: db+mysql://root:${ROOT_PASSWORD}@mysql_container:3306/airflow_db
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
            # - REDIS_PASSWORD=redispass
        command: worker
        env_file:
            - .env
