CREATE ROLE admingroup, config_manager, operation_manager, operation_viewer;
GRANT ALL ON airflow_db.* TO admingroup;
GRANT SELECT ON airflow_db.* TO operation_viewer;
GRANT SELECT ON airflow_db.* TO config_manager;
GRANT INSERT, UPDATE, DELETE ON airflow_db.* TO config_manager;
GRANT SELECT ON airflow_db.* TO operation_manager;
GRANT INSERT, UPDATE, DELETE ON airflow_db.* TO operation_manager;
CREATE USER talendsrv IDENTIFIED BY 'talendsrv@123';
CREATE USER talenduser IDENTIFIED BY 'talenduser@123';
CREATE USER talendadmin IDENTIFIED BY 'talendadmin@123';
CREATE USER talendconfig IDENTIFIED BY 'talendconfig@123';
CREATE USER talendviewer IDENTIFIED BY 'talendviewer@123';
GRANT operation_manager TO talendsrv;
GRANT operation_manager TO talenduser;
GRANT admingroup TO talendadmin;
GRANT config_manager TO talendconfig;
GRANT operation_viewer TO talendviewer;
SET DEFAULT ROLE ALL TO talendsrv;
SET DEFAULT ROLE ALL TO talenduser;
SET DEFAULT ROLE ALL TO talendadmin;
SET DEFAULT ROLE ALL TO talendconfig;
SET DEFAULT ROLE ALL TO talendviewer;
